site_name: Programming Bits

theme:
  name: material
  features:
    - navigation.footer

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: ${GA4_ID}
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/viagostini
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/viniciusagostini/?locale=en_US

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
